<?php
$z[0]=Array("channel","\r\n      <li> <a href=\"[field:typeurl/]\">[field:typename/]</a> </li>\r\n      ",111,226);
$z[0][4]['type']="top";
$z[1]=Array("flink","  [field:link /]  ",373,451);
$z[1][4]['titlelen']="20";
$z[1][4]['row']="20";
$z[1][4]['type']="text";
$z[2]=Array("global","",735,759);
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",777,803);
$z[3][4]['name']="cfg_powerby";

?>